### ISSUE TITLE
Check whether a node is inside the camera frustum

### ISSUE THREAD

**Issue by siamonas** [SFraissTU/BA_PointCloud#13]
Hello Simon,

First of all, I would like to thank you for developing this project. It is quite impressive!

So, I was trying to dive into the specifics of your project and I found it difficult to understand the physical meaning of a utility function you use to check whether a node lies within the camera frustum or not. I'm talking about the **Util.InsideFrustum(BoundingBox box, Plane[] frustum)** function.

I stuck onto this when the root node of my potree file was being rendered, while my camera was lying outside the bounding box of the root node and looking away from the root node. 

It seems that your function renders a node **if every single vertex lies on the positive side of just one (not the same each time) plane of the camera frustum**.

I think that the functionality you were looking for is to **render a node if one of its vertices lies on the positive side of each and every plane of the camera frustum**. Is that right? The thing is that you might not be able to see the root node (and all of its children) in case the camera is on the edges of the bounding box looking away from the node.

Also, I noticed you have another function **Util.InsideFrustum(Vector3 vec, Plane[] frustum)** that checks if a vector lies within the camera frustum. This implementation is actually correct.

I tried to optimize what is rendered by rearranging the checks as follows:

- **If the camera position lies within the cirumscribed sphere of a node, the node is rendered.** This way, we can always render the root node.
- **If one of the vertices of the bounding box OR the center of a node lie within the camera frustum (using the second Util.InsideFrustum), the node is rendered.** 

What are your thoughts on the topic? I could submit a pull request if you want.

Have a nice one,
Stavros

Edit: Explain better the situation

**Comment by SFraissTU** [comment]
Hi!
Thanks for pointing this out. Yes, what you write seems correct. This should be different, the idea is that at least one of the vertices should be inside the view frustum (so it should lie on all positive sides). I'm confused right now that it still seemed to work quite correctly, because right now this seems to me as if the function would return true most of the times.
I currently don't really have time to look into it further (hopefully I will find some time this month though), so feel free to submit a pull request.
Simon

**Comment by SFraissTU** [comment]
So I took a look at your pull request and it seemed to me that it doesn't change much, so I looked into my InsideFrustum function again. And I think you understood it wrong. What you said before is that my function renders a node if every single vertex lies on the positive side of at least one of the planes. That is actually not true. Because in that case, it would render everything all the time, as there is no vertex that is not on the positive side of any of the five planes (I think). It actually renders a node if _for each plane_, at least one vertex lies on the positive side.
We can also phrase this the other way round: A node is not rendered, if and only if there is a plane, for which all vertices lie on the negative side. And this approach makes a lot of sense and it's also not necessary that you check the middle point of the bounding box, as even if all box vertices are actually outside of the view frustum, the node still gets rendered, as for each plane there is at least one vertex on it's positive side. This wouldn't be the case with your method, as at least one of the vertices or the middle point has to be inside the frustum.
I also drew a small sketch illustrating this in the 2d-case: http://sryus.atria.uberspace.de/frustum.jpg (sorry, my handwriting is not the most beautiful one).
I hope this makes it clear.
Simon

**Comment by SFraissTU** [comment]
That being said, I'm aware that sometimes it seems like the root node is rendered even though, the camera is outside and looking into another direction. So there seems to be something fishy in there. But that function seems correct to me right now.
If you think otherwise, please let me know.

**Comment by siamonas** [comment]
Hi again,

I read what I wrote above and it doesn't make totally sense. Excuse me for that.

What I wanted to say is exactly what you pointed out.
> It actually renders a node if for each plane, at least one vertex lies on the positive side.

However, it seems more simple and natural to **render a node if and only if a vertex of its bounding box lies on the positive side of all camera frustum planes**. (and that is what my pull request is about)

The problem with your utility function is in the very meaning of **what lies on the positive side of a plane**. I also made a [sketch](https://docs.google.com/drawings/d/1ATHQaFQJ8VOjQOOqV_OaKGFJrGLJHJBYQLG2Be1fq-s/edit) illustrating a case where the camera is outisde the bounding box of the root node, looking the other way around and the root node gets rendered.

The sketch illustrates the camera frustum (on 2D). The camera frustum comprises four (4) planes in 2D. The dotted lines resemble the extension of each plane up to infinity. I have also drawn the normals of each plane facing towards the positive side of each plane. Lastly, we have the bounding box of the root node on the lower left side of the sketch. There is one plane (the right one) which is drawn with a red dotted line. This plane is the reason why the root node is rendered. The vertices of the root node bounding box lie on the positive side of the right plane of the camera frustum (because the plane is assumed to extend to infinity).

> I'm aware that sometimes it seems like the root node is rendered even though, the camera is outside and looking into another direction. So there seems to be something fishy in there.

Extending our undestanding of this situation, we should expect many unwanted (lying behind the camera) nodes to be rendered. This has a direct adverse effect to the performance of your code. What I proposed in the pull request is more optimized and actually more simple.

A node is rendered:
- If the camera is inside that node,
- If the center of the node bounding box is inside the camera frustum (maybe this is not crucial), and
- If a vertex of the node bounding box is inside the camera frustum.

Where **inside the camera frustum** means that a point/vertex lies on the positive side of all camera frustum planes simultaneously.

These are my thoughts on the issue.

I'm eager to hear your feedback,
Stavros

**Comment by SFraissTU** [comment]
Hi! Thanks for your reply!

>  I also made a sketch illustrating a case where the camera is outisde the bounding box of the root node, looking the other way around and the root node gets rendered.

If I'm not mistaken, in your example the root node is precisely _not_ rendered with my method. As I said, **for a node to be rendered, for each plane one of the bounding box vertices has to lie on the positive side**. This is not the case in your example for the near plane. All bounding box vertices lie on the negative side of the near plane. So in my InsideFrustum-function, the variable "inside" would be false and the if in line 34 would be executed, which results in the function returning false for that example.

It is not sufficient that the vertices lie on the positive side of just one plane, as you seem to think. Instead it is necessary that for each plane one vertex has to lie on it's positive side, and that is not the case here. Please take a look at my code again.

> However, it seems more simple and natural to render a node if and only if a vertex of its bounding box lies on the positive side of all camera frustum planes.

Seems to make sense at first glance, but the problem is, that it's possible that none of the vertices is inside the view frustum. And there could also be cases, where the vertices are not inside the frustum _and_ the camera is not even in the bounding box, and yet it should be rendered. See [this](https://docs.google.com/drawings/d/1Hj195mFxFVUPk6iWnpu6r5dHNQLB96W_-wY5rJWfI8s/edit?usp=sharing) example (and thanks for pointing out google drawings to me, I didn't know that yet!).

> Extending our undestanding of this situation, we should expect many unwanted (lying behind the camera) nodes to be rendered. This has a direct adverse effect to the performance of your code. What I proposed in the pull request is more optimized and actually more simple.

Well you can check it yourself. If you switch from the Game to the Scene-Tab in Unity while the application is running (or open both at the same time), you see that this is usually not the case. There are a few nodes that seem to be rendered a tiny bit too soon, but it's hard to guess just by eye sight, maybe the bounding box is actually already intersecting the frustum. See [this screenshot](https://drive.google.com/file/d/1L9fD-JFKJzFswgNXAYaQ17PsQBtyfIDB/view?usp=sharing) as an example. If there is a problem, it is less dramatic than what you seem to think.

However you are definitely right about one thing: Simply checking if the camera is inside the node in the beginning is indeed an elegant solution and we will get rid of many computations in a lot of cases.

I hope this clears things for you a bit. Otherwise, keep the discussion going, I'm enjoying it.

Cheers, Simon

**Comment by siamonas** [comment]
Hi again,

We are having quite a conversation here and I really like it.

Unfortunately, I'll be out of town for a week or so. I will come back with example scenes and a comment here next Wednesday.

Have a nice one,
Stavros

**Comment by siamonas** [comment]
Greetings,

Sorry for my late response.

> If I'm not mistaken, in your example the root node is precisely not rendered with my method.
To be honest, that is correct. 

What you're saying is actually correct. However, the example point cloud isn't representative of the point clouds I am working with. I am attaching two pictures presenting a point cloud of a enclosed industrial space. The first picture presents the scene view using the raw code of yours, while the second illustrates the same point cloud but with the alternations I did to the utility function.

![1_raw_code](https://user-images.githubusercontent.com/13619515/63248762-baf11c00-c270-11e9-95b2-c9f06ee6e993.png)
![2_altered_code](https://user-images.githubusercontent.com/13619515/63248761-ba588580-c270-11e9-941e-ee4a6a99c50e.png)

It can be seen that in the second picture only two nodes are rendered (root node and one of its children) because their shared bounding box vertex (in red) is inside the camera frustum. In the first picture, additional nodes are rendered without actually needing to be rendered.

If you think this isn't an improvement for your code, feel free to close this issue (and the respective pull request).

Have a nice one,
Stavros
