### ISSUE TITLE
on build i have to manually adjust the folderstructure to load the pointcloud

### ISSUE THREAD

**Issue by lfscetvr** [SFraissTU/BA_PointCloud#21]
i place the clouds in a the StreamingAssets directory.
after build the player wont find the pointcloud since it is hidden away in the data folder.
if i move the StreamingAssets folder to a folder named Assets in the build's root than it will run normaly and show the pointcloud when i run the player.

is there a way that i can build from unity and that these steps are not needed or should i automate these steps?

**Comment by SFraissTU** [comment]
Hi! Streaming Assets are now supported. In the Point Cloud Loader and Directory Loader components there is a "Streaming Assets as root" property. If this is set to true the cloudPath is understood as a relative path from the StreamingAssets directory.
I hope this helps, I don't know much about Unity's StreamingAssets functionality. And I acknowledge that it's been a while since this question was asked, so it might not be of much use to you anymore.
